services:
  web:
    build: .
    expose:
    - "5005"
    depends_on:
    - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
  redis:
    image: redis:latest
    ports: 
    - "6379:6379"
    volumes:
    - redis_data:/data

  nginx:
   image: nginx:latest
   ports:
    - "5005:5005"
   volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
   depends_on:
    - web


volumes:
  redis_data:
  

