
services:
  web:
    image: my-flask-app:multistage-chatgpt
    ports:
      - "5000:5000"
    depends_on:
      - mydb

  mydb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw